# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

env:
  global:
    - PYTORCH_VERSION="1.0"

r-packages:
  - logging
  - reticulate
  - jsonlite
  - R6
  - rstudioapi
  - data.table


before_script:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - rm miniconda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - R -e 'rTorch::install_pytorch(method="conda", version=Sys.getenv("PYTORCH_VERSION"), channel="pytorch", conda_python_version="3.7")'
  - R CMD INSTALL .

